package com.teamresourceful.resourcefulintegration.peripherals;

import com.teamresourceful.resourcefulintegration.utils.PreprocessedReplaced;
import org.lwjgl.input.Keyboard;

@PreprocessedReplaced
@SuppressWarnings("unused")
public final class Keys {

    private Keys() {
        throw new IllegalStateException("Utility class");
    }

    public static final Key NONE = new Key(Keyboard.KEY_NONE);
    public static final Key ESCAPE = new Key(Keyboard.KEY_ESCAPE);
    public static final Key ONE = new Key(Keyboard.KEY_1);
    public static final Key TWO = new Key(Keyboard.KEY_2);
    public static final Key THREE = new Key(Keyboard.KEY_3);
    public static final Key FOUR = new Key(Keyboard.KEY_4);
    public static final Key FIVE = new Key(Keyboard.KEY_5);
    public static final Key SIX = new Key(Keyboard.KEY_6);
    public static final Key SEVEN = new Key(Keyboard.KEY_7);
    public static final Key EIGHT = new Key(Keyboard.KEY_8);
    public static final Key NINE = new Key(Keyboard.KEY_9);
    public static final Key ZERO = new Key(Keyboard.KEY_0);
    public static final Key MINUS = new Key(Keyboard.KEY_MINUS);
    public static final Key EQUALS = new Key(Keyboard.KEY_EQUALS);
    public static final Key BACK = new Key(Keyboard.KEY_BACK);
    public static final Key TAB = new Key(Keyboard.KEY_TAB);
    public static final Key Q = new Key(Keyboard.KEY_Q);
    public static final Key W = new Key(Keyboard.KEY_W);
    public static final Key E = new Key(Keyboard.KEY_E);
    public static final Key R = new Key(Keyboard.KEY_R);
    public static final Key T = new Key(Keyboard.KEY_T);
    public static final Key Y = new Key(Keyboard.KEY_Y);
    public static final Key U = new Key(Keyboard.KEY_U);
    public static final Key I = new Key(Keyboard.KEY_I);
    public static final Key O = new Key(Keyboard.KEY_O);
    public static final Key P = new Key(Keyboard.KEY_P);
    public static final Key LBRACKET = new Key(Keyboard.KEY_LBRACKET);
    public static final Key RBRACKET = new Key(Keyboard.KEY_RBRACKET);
    public static final Key RETURN = new Key(Keyboard.KEY_RETURN);
    public static final Key LCONTROL = new Key(Keyboard.KEY_LCONTROL);
    public static final Key A = new Key(Keyboard.KEY_A);
    public static final Key S = new Key(Keyboard.KEY_S);
    public static final Key D = new Key(Keyboard.KEY_D);
    public static final Key F = new Key(Keyboard.KEY_F);
    public static final Key G = new Key(Keyboard.KEY_G);
    public static final Key H = new Key(Keyboard.KEY_H);
    public static final Key J = new Key(Keyboard.KEY_J);
    public static final Key K = new Key(Keyboard.KEY_K);
    public static final Key L = new Key(Keyboard.KEY_L);
    public static final Key SEMICOLON = new Key(Keyboard.KEY_SEMICOLON);
    public static final Key APOSTROPHE = new Key(Keyboard.KEY_APOSTROPHE);
    public static final Key GRAVE = new Key(Keyboard.KEY_GRAVE);
    public static final Key LSHIFT = new Key(Keyboard.KEY_LSHIFT);
    public static final Key BACKSLASH = new Key(Keyboard.KEY_BACKSLASH);
    public static final Key Z = new Key(Keyboard.KEY_Z);
    public static final Key X = new Key(Keyboard.KEY_X);
    public static final Key C = new Key(Keyboard.KEY_C);
    public static final Key V = new Key(Keyboard.KEY_V);
    public static final Key B = new Key(Keyboard.KEY_B);
    public static final Key N = new Key(Keyboard.KEY_N);
    public static final Key M = new Key(Keyboard.KEY_M);
    public static final Key COMMA = new Key(Keyboard.KEY_COMMA);
    public static final Key PERIOD = new Key(Keyboard.KEY_PERIOD);
    public static final Key SLASH = new Key(Keyboard.KEY_SLASH);
    public static final Key RSHIFT = new Key(Keyboard.KEY_RSHIFT);
    public static final Key MULTIPLY = new Key(Keyboard.KEY_MULTIPLY);
    public static final Key LMENU = new Key(Keyboard.KEY_LMENU);
    public static final Key SPACE = new Key(Keyboard.KEY_SPACE);
    public static final Key CAPITAL = new Key(Keyboard.KEY_CAPITAL);
    public static final Key F1 = new Key(Keyboard.KEY_F1);
    public static final Key F2 = new Key(Keyboard.KEY_F2);
    public static final Key F3 = new Key(Keyboard.KEY_F3);
    public static final Key F4 = new Key(Keyboard.KEY_F4);
    public static final Key F5 = new Key(Keyboard.KEY_F5);
    public static final Key F6 = new Key(Keyboard.KEY_F6);
    public static final Key F7 = new Key(Keyboard.KEY_F7);
    public static final Key F8 = new Key(Keyboard.KEY_F8);
    public static final Key F9 = new Key(Keyboard.KEY_F9);
    public static final Key F10 = new Key(Keyboard.KEY_F10);
    public static final Key NUMLOCK = new Key(Keyboard.KEY_NUMLOCK);
    public static final Key SCROLL = new Key(Keyboard.KEY_SCROLL);
    public static final Key NUMPAD7 = new Key(Keyboard.KEY_NUMPAD7);
    public static final Key NUMPAD8 = new Key(Keyboard.KEY_NUMPAD8);
    public static final Key NUMPAD9 = new Key(Keyboard.KEY_NUMPAD9);
    public static final Key SUBTRACT = new Key(Keyboard.KEY_SUBTRACT);
    public static final Key NUMPAD4 = new Key(Keyboard.KEY_NUMPAD4);
    public static final Key NUMPAD5 = new Key(Keyboard.KEY_NUMPAD5);
    public static final Key NUMPAD6 = new Key(Keyboard.KEY_NUMPAD6);
    public static final Key ADD = new Key(Keyboard.KEY_ADD);
    public static final Key NUMPAD1 = new Key(Keyboard.KEY_NUMPAD1);
    public static final Key NUMPAD2 = new Key(Keyboard.KEY_NUMPAD2);
    public static final Key NUMPAD3 = new Key(Keyboard.KEY_NUMPAD3);
    public static final Key NUMPAD0 = new Key(Keyboard.KEY_NUMPAD0);
    public static final Key DECIMAL = new Key(Keyboard.KEY_DECIMAL);
    public static final Key F11 = new Key(Keyboard.KEY_F11);
    public static final Key F12 = new Key(Keyboard.KEY_F12);
    public static final Key F13 = new Key(Keyboard.KEY_F13);
    public static final Key F14 = new Key(Keyboard.KEY_F14);
    public static final Key F15 = new Key(Keyboard.KEY_F15);
    public static final Key F16 = new Key(Keyboard.KEY_F16);
    public static final Key F17 = new Key(Keyboard.KEY_F17);
    public static final Key F18 = new Key(Keyboard.KEY_F18);
    public static final Key KANA = new Key(Keyboard.KEY_KANA);
    public static final Key F19 = new Key(Keyboard.KEY_F19);
    public static final Key CONVERT = new Key(Keyboard.KEY_CONVERT);
    public static final Key NOCONVERT = new Key(Keyboard.KEY_NOCONVERT);
    public static final Key YEN = new Key(Keyboard.KEY_YEN);
    public static final Key NUMPADEQUALS = new Key(Keyboard.KEY_NUMPADEQUALS);
    public static final Key CIRCUMFLEX = new Key(Keyboard.KEY_CIRCUMFLEX);
    public static final Key AT = new Key(Keyboard.KEY_AT);
    public static final Key COLON = new Key(Keyboard.KEY_COLON);
    public static final Key UNDERLINE = new Key(Keyboard.KEY_UNDERLINE);
    public static final Key KANJI = new Key(Keyboard.KEY_KANJI);
    public static final Key STOP = new Key(Keyboard.KEY_STOP);
    public static final Key AX = new Key(Keyboard.KEY_AX);
    public static final Key UNLABELED = new Key(Keyboard.KEY_UNLABELED);
    public static final Key NUMPADENTER = new Key(Keyboard.KEY_NUMPADENTER);
    public static final Key RCONTROL = new Key(Keyboard.KEY_RCONTROL);
    public static final Key SECTION = new Key(Keyboard.KEY_SECTION);
    public static final Key NUMPADCOMMA = new Key(Keyboard.KEY_NUMPADCOMMA);
    public static final Key DIVIDE = new Key(Keyboard.KEY_DIVIDE);
    public static final Key SYSRQ = new Key(Keyboard.KEY_SYSRQ);
    public static final Key RMENU = new Key(Keyboard.KEY_RMENU);
    public static final Key FUNCTION = new Key(Keyboard.KEY_FUNCTION);
    public static final Key PAUSE = new Key(Keyboard.KEY_PAUSE);
    public static final Key HOME = new Key(Keyboard.KEY_HOME);
    public static final Key UP = new Key(Keyboard.KEY_UP);
    public static final Key PRIOR = new Key(Keyboard.KEY_PRIOR);
    public static final Key LEFT = new Key(Keyboard.KEY_LEFT);
    public static final Key RIGHT = new Key(Keyboard.KEY_RIGHT);
    public static final Key END = new Key(Keyboard.KEY_END);
    public static final Key DOWN = new Key(Keyboard.KEY_DOWN);
    public static final Key NEXT = new Key(Keyboard.KEY_NEXT);
    public static final Key INSERT = new Key(Keyboard.KEY_INSERT);
    public static final Key DELETE = new Key(Keyboard.KEY_DELETE);
    public static final Key CLEAR = new Key(Keyboard.KEY_CLEAR);
    public static final Key LMETA = new Key(Keyboard.KEY_LMETA);
    public static final Key RMETA = new Key(Keyboard.KEY_RMETA);
    public static final Key APPS = new Key(Keyboard.KEY_APPS);
    public static final Key POWER = new Key(Keyboard.KEY_POWER);
    public static final Key SLEEP = new Key(Keyboard.KEY_SLEEP);
}
